function [] = old_menu()
    %% 交互界面
    stop = false;

    while(stop == false)        
        % interactive_ui();
        % break;

        % sel = menu('演示界面菜单',...
        %     '无噪声：估计偏差-信号频率',...
        %     '有噪声：高信噪比下，RMS误差-信号频率',...
        %     '有噪声：低信噪比下，RMS误差-信号频率',...
        %     '有噪声：RMS误差-信噪比',...
        %     '有噪声：不同噪声类型，RMS误差-信噪比',...
        %     '有噪声：不同窗函数，RMS误差-信噪比',...
        %     '有干扰：高信干比下，估计偏差-干扰相对位置',...
        %     '有干扰：低信干比下，估计偏差-干扰相对位置',...
        %     '有干扰：估计偏差-信干比',...
        %     '自定义模式',...
        %     'Exit',...
        %     '窗口');

        % 替换原始的menu函数为更美观的listdlg
        options = {
            '无噪声：估计偏差-信号频率',...
            '有噪声：高信噪比下，RMS误差-信号频率',...
            '有噪声：低信噪比下，RMS误差-信号频率',...
            '有噪声：RMS误差-信噪比',...
            '有噪声：不同噪声类型，RMS误差-信噪比',...
            '有噪声：不同窗函数，RMS误差-信噪比',...
            '有干扰：高信干比下，估计偏差-干扰相对位置',...
            '有干扰：低信干比下，估计偏差-干扰相对位置',...
            '有干扰：估计偏差-信干比',...
            '自定义模式',...
            'Exit',...
            '窗口'};
        
        [sel, ok] = listdlg(...
            'PromptString', '请选择演示模式 (可单选)',...
            'ListString', options,...
            'SelectionMode', 'single',...
            'ListSize', [300 200],...  % 调整弹窗大小
            'Name', '演示界面菜单');
        
        if ~ok  % 如果用户取消选择
            break;
        end

        stop = old_run_estimate(sel);
        if stop
            break;
        end

        % 添加等待环节
        h = uicontrol('Style', 'pushbutton', 'String', '返回菜单',...
                     'Position', [10 10 100 30],...
                     'Callback', 'uiresume(gcbf)');
        uiwait(gcf);  % 暂停直到点击按钮
        delete(h);    % 删除临时按钮

    end
end