function selection = main_menu()
    stop = false;

    while(stop == false)  
        % 替换原始的menu函数为更美观的listdlg
        options = {
            '比较不同窗函数的影响',...
            '比较目标信号落入不同间隔时的性能',...
            '比较不同SNR下的影响',...
            '比较不同干扰大小下的性能',...
            '比较不同干扰间隔下的性能',...
            '比较噪声/干扰服从不同概率分布函数的性能',...
            '比较不同频率估计算法的性能'};
        
        [sel, ok] = listdlg(...
            'PromptString', '请选择仿真方法',...
            'ListString', options,...
            'SelectionMode', 'single',...
            'ListSize', [400 300],...  % 调整弹窗大小
            'Name', '仿真选项菜单');
        
        if ~ok  % 如果用户取消选择
            break;
        end

        stop = run_estimate(sel);
        if stop
            break;
        end

        % 添加等待环节
        h = uicontrol('Style', 'pushbutton', 'String', '返回菜单',...
                       'Position', [10 10 100 30],...
                       'Callback', 'uiresume(gcbf)');
        uiwait(gcf);  % 暂停直到点击按钮
        delete(h);    % 删除临时按钮
    end
end